DOTTEDLINE_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
DOTTEDLINE_SRC := $(DOTTEDLINE_DIR)/src/8b10b.c
DOTTEDLINE_INC := -I$(DOTTEDLINE_DIR)/src
$(info Using dottedline $(DOTTEDLINE_DIR))

# autogenerated
$(DOTTEDLINE_DIR)/src/8b10btables.h: $(DOTTEDLINE_DIR)/eightbtenb/__init__.py
	python3 $< > $@

$(DOTTEDLINE_SRC): $(DOTTEDLINE_DIR)/src/8b10btables.h

