/* 8b10b encoding/decoding tables, generated by __init__.py */

static const unsigned int invertDataBit = 7, invertRdBit = 6;

/* EDCBA lookup table, indexed by EDCBA input (A is least significant bit),
     * outputs: invert value (1 bit, ~), invert rd (1 bit, N), iedcba (6 bits, for
     * positive RD, a is least significant bit)
     */
static const uint8_t fivebsixbEncTbl[] = {
	      /*      ~Niedcba */
	0xc6, /* D 0: 11000110 */
	0xd1, /* D 1: 11010001 */
	0xd2, /* D 2: 11010010 */
	0x23, /* D 3: 00100011 */
	0xd4, /* D 4: 11010100 */
	0x25, /* D 5: 00100101 */
	0x26, /* D 6: 00100110 */
	0xb8, /* D 7: 10111000 */
	0xd8, /* D 8: 11011000 */
	0x29, /* D 9: 00101001 */
	0x2a, /* D10: 00101010 */
	0x0b, /* D11: 00001011 */
	0x2c, /* D12: 00101100 */
	0x0d, /* D13: 00001101 */
	0x0e, /* D14: 00001110 */
	0xc5, /* D15: 11000101 */
	0xc9, /* D16: 11001001 */
	0x31, /* D17: 00110001 */
	0x32, /* D18: 00110010 */
	0x13, /* D19: 00010011 */
	0x34, /* D20: 00110100 */
	0x15, /* D21: 00010101 */
	0x16, /* D22: 00010110 */
	0xe8, /* D23: 11101000 */
	0xcc, /* D24: 11001100 */
	0x19, /* D25: 00011001 */
	0x1a, /* D26: 00011010 */
	0xe4, /* D27: 11100100 */
	0x1c, /* D28: 00011100 */
	0xe2, /* D29: 11100010 */
	0xe1, /* D30: 11100001 */
	0xca, /* D31: 11001010 */
	};

/* HGF lookup table, indexed by HGF input (F is least significant bit), see
     * above.
     */
static const uint8_t threebfourbEncTbl[] = {
	      /*       ~NXXjhgf */
	0xc2, /* Dx.0: 11000010 */
	0x09, /* Dx.1: 00001001 */
	0x0a, /* Dx.2: 00001010 */
	0x8c, /* Dx.3: 10001100 */
	0xc4, /* Dx.4: 11000100 */
	0x05, /* Dx.5: 00000101 */
	0x06, /* Dx.6: 00000110 */
	0xc8, /* Dx.7: 11001000 */
	};

/* iedcba lookup table, values are decoded data */
static const uint8_t fivebsixbDecTbl[] = {
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	0x0f, /* D15 */
	0x00, /* D 0 */
	0x07, /* D 7 */
	0xff, /* unused */
	0x10, /* D16 */
	0x1f, /* D31 */
	0x0b, /* D11 */
	0x18, /* D24 */
	0x0d, /* D13 */
	0x0e, /* D14 */
	0xff, /* unused */
	0xff, /* unused */
	0x01, /* D 1 */
	0x02, /* D 2 */
	0x13, /* D19 */
	0x04, /* D 4 */
	0x15, /* D21 */
	0x16, /* D22 */
	0x17, /* D23 */
	0x08, /* D 8 */
	0x19, /* D25 */
	0x1a, /* D26 */
	0x1b, /* D27 */
	0x1c, /* D28 */
	0x1d, /* D29 */
	0x1e, /* D30 */
	0xff, /* unused */
	0xff, /* unused */
	0x1e, /* D30 */
	0x1d, /* D29 */
	0x03, /* D 3 */
	0x1b, /* D27 */
	0x05, /* D 5 */
	0x06, /* D 6 */
	0x08, /* D 8 */
	0x17, /* D23 */
	0x09, /* D 9 */
	0x0a, /* D10 */
	0x04, /* D 4 */
	0x0c, /* D12 */
	0x02, /* D 2 */
	0x01, /* D 1 */
	0xff, /* unused */
	0xff, /* unused */
	0x11, /* D17 */
	0x12, /* D18 */
	0x18, /* D24 */
	0x14, /* D20 */
	0x1f, /* D31 */
	0x10, /* D16 */
	0xff, /* unused */
	0x07, /* D 7 */
	0x00, /* D 0 */
	0x0f, /* D15 */
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	0xff, /* unused */
	};

/* jhgf lookup table, values are decoded data */
static const uint8_t threebfourbDecTbl[] = {
	0xff, /* unused */
	0xff, /* unused */
	0x00, /* Dx. 0 */
	0x03, /* Dx. 3 */
	0x04, /* Dx. 4 */
	0x05, /* Dx. 5 */
	0x06, /* Dx. 6 */
	0x07, /* Dx. 7 */
	0x07, /* Dx. 7 */
	0x01, /* Dx. 1 */
	0x02, /* Dx. 2 */
	0x04, /* Dx. 4 */
	0x03, /* Dx. 3 */
	0x00, /* Dx. 0 */
	0xff, /* unused */
	0xff, /* unused */
	};

